using Unity.Collections.LowLevel.Unsafe;
using Unity.Entities;
using Unity.Collections;
using Unity.NetCode;
using Unity.Transforms;
using Unity.Rendering;
using UnityEngine;

public struct ThirdPersonControllerGhostSerializer : IGhostSerializer<ThirdPersonControllerSnapshotData>
{
    private ComponentType componentTypeMovablePlayer;
    private ComponentType componentTypeLocalToWorld;
    private ComponentType componentTypeRotation;
    private ComponentType componentTypeTranslation;
    private ComponentType componentTypeLinkedEntityGroup;
    // FIXME: These disable safety since all serializers have an instance of the same type - causing aliasing. Should be fixed in a cleaner way
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ArchetypeChunkComponentType<MovablePlayer> ghostMovablePlayerType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ArchetypeChunkComponentType<Rotation> ghostRotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ArchetypeChunkComponentType<Translation> ghostTranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ArchetypeChunkBufferType<LinkedEntityGroup> ghostLinkedEntityGroupType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild0RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild0TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild1RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild1TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild2RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild2TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild3RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild3TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild4RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild4TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild5RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild5TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild6RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild6TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild7RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild7TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild8RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild8TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild9RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild9TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild10RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild10TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild11RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild11TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild12RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild12TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild13RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild13TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild14RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild14TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild15RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild15TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild16RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild16TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild17RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild17TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild18RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild18TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild19RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild19TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild20RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild20TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild21RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild21TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild22RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild22TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild23RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild23TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild24RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild24TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild25RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild25TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild26RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild26TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild27RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild27TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild28RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild28TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild29RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild29TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild30RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild30TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild31RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild31TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild32RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild32TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild33RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild33TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild34RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild34TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild35RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild35TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild36RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild36TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild37RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild37TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild38RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild38TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild39RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild39TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild40RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild40TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild41RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild41TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild42RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild42TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild43RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild43TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild44RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild44TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild45RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild45TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild46RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild46TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild47RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild47TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild48RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild48TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild49RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild49TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild50RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild50TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild51RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild51TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild52RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild52TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild53RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild53TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild54RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild54TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild55RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild55TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild56RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild56TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild57RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild57TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild58RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild58TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild59RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild59TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild60RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild60TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild61RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild61TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild62RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild62TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild63RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild63TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild64RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild64TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild65RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild65TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild66RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild66TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild67RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild67TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild68RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild68TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild69RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild69TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild70RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild70TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild71RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild71TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild72RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild72TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild73RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild73TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild74RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild74TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild75RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild75TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild76RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild76TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild77RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild77TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild78RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild78TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild79RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild79TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild80RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild80TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild81RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild81TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild82RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild82TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild83RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild83TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild84RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild84TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild85RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild85TranslationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Rotation> ghostChild86RotationType;
    [NativeDisableContainerSafetyRestriction][ReadOnly] private ComponentDataFromEntity<Translation> ghostChild86TranslationType;


    public int CalculateImportance(ArchetypeChunk chunk)
    {
        return 1;
    }

    public int SnapshotSize => UnsafeUtility.SizeOf<ThirdPersonControllerSnapshotData>();
    public void BeginSerialize(ComponentSystemBase system)
    {
        componentTypeMovablePlayer = ComponentType.ReadWrite<MovablePlayer>();
        componentTypeLocalToWorld = ComponentType.ReadWrite<LocalToWorld>();
        componentTypeRotation = ComponentType.ReadWrite<Rotation>();
        componentTypeTranslation = ComponentType.ReadWrite<Translation>();
        componentTypeLinkedEntityGroup = ComponentType.ReadWrite<LinkedEntityGroup>();
        ghostMovablePlayerType = system.GetArchetypeChunkComponentType<MovablePlayer>(true);
        ghostRotationType = system.GetArchetypeChunkComponentType<Rotation>(true);
        ghostTranslationType = system.GetArchetypeChunkComponentType<Translation>(true);
        ghostLinkedEntityGroupType = system.GetArchetypeChunkBufferType<LinkedEntityGroup>(true);
        ghostChild0RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild0TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild1RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild1TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild2RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild2TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild3RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild3TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild4RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild4TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild5RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild5TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild6RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild6TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild7RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild7TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild8RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild8TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild9RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild9TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild10RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild10TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild11RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild11TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild12RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild12TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild13RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild13TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild14RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild14TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild15RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild15TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild16RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild16TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild17RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild17TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild18RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild18TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild19RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild19TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild20RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild20TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild21RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild21TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild22RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild22TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild23RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild23TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild24RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild24TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild25RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild25TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild26RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild26TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild27RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild27TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild28RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild28TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild29RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild29TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild30RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild30TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild31RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild31TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild32RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild32TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild33RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild33TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild34RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild34TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild35RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild35TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild36RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild36TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild37RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild37TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild38RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild38TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild39RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild39TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild40RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild40TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild41RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild41TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild42RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild42TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild43RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild43TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild44RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild44TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild45RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild45TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild46RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild46TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild47RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild47TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild48RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild48TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild49RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild49TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild50RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild50TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild51RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild51TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild52RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild52TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild53RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild53TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild54RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild54TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild55RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild55TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild56RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild56TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild57RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild57TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild58RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild58TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild59RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild59TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild60RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild60TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild61RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild61TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild62RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild62TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild63RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild63TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild64RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild64TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild65RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild65TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild66RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild66TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild67RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild67TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild68RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild68TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild69RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild69TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild70RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild70TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild71RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild71TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild72RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild72TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild73RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild73TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild74RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild74TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild75RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild75TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild76RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild76TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild77RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild77TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild78RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild78TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild79RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild79TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild80RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild80TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild81RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild81TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild82RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild82TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild83RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild83TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild84RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild84TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild85RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild85TranslationType = system.GetComponentDataFromEntity<Translation>(true);
        ghostChild86RotationType = system.GetComponentDataFromEntity<Rotation>(true);
        ghostChild86TranslationType = system.GetComponentDataFromEntity<Translation>(true);
    }

    public void CopyToSnapshot(ArchetypeChunk chunk, int ent, uint tick, ref ThirdPersonControllerSnapshotData snapshot, GhostSerializerState serializerState)
    {
        snapshot.tick = tick;
        var chunkDataMovablePlayer = chunk.GetNativeArray(ghostMovablePlayerType);
        var chunkDataRotation = chunk.GetNativeArray(ghostRotationType);
        var chunkDataTranslation = chunk.GetNativeArray(ghostTranslationType);
        var chunkDataLinkedEntityGroup = chunk.GetBufferAccessor(ghostLinkedEntityGroupType);
        snapshot.SetMovablePlayerPlayerId(chunkDataMovablePlayer[ent].PlayerId, serializerState);
        snapshot.SetRotationValue(chunkDataRotation[ent].Value, serializerState);
        snapshot.SetTranslationValue(chunkDataTranslation[ent].Value, serializerState);
        snapshot.SetChild0RotationValue(ghostChild0RotationType[chunkDataLinkedEntityGroup[ent][1].Value].Value, serializerState);
        snapshot.SetChild0TranslationValue(ghostChild0TranslationType[chunkDataLinkedEntityGroup[ent][1].Value].Value, serializerState);
        snapshot.SetChild1RotationValue(ghostChild1RotationType[chunkDataLinkedEntityGroup[ent][2].Value].Value, serializerState);
        snapshot.SetChild1TranslationValue(ghostChild1TranslationType[chunkDataLinkedEntityGroup[ent][2].Value].Value, serializerState);
        snapshot.SetChild2RotationValue(ghostChild2RotationType[chunkDataLinkedEntityGroup[ent][3].Value].Value, serializerState);
        snapshot.SetChild2TranslationValue(ghostChild2TranslationType[chunkDataLinkedEntityGroup[ent][3].Value].Value, serializerState);
        snapshot.SetChild3RotationValue(ghostChild3RotationType[chunkDataLinkedEntityGroup[ent][4].Value].Value, serializerState);
        snapshot.SetChild3TranslationValue(ghostChild3TranslationType[chunkDataLinkedEntityGroup[ent][4].Value].Value, serializerState);
        snapshot.SetChild4RotationValue(ghostChild4RotationType[chunkDataLinkedEntityGroup[ent][5].Value].Value, serializerState);
        snapshot.SetChild4TranslationValue(ghostChild4TranslationType[chunkDataLinkedEntityGroup[ent][5].Value].Value, serializerState);
        snapshot.SetChild5RotationValue(ghostChild5RotationType[chunkDataLinkedEntityGroup[ent][6].Value].Value, serializerState);
        snapshot.SetChild5TranslationValue(ghostChild5TranslationType[chunkDataLinkedEntityGroup[ent][6].Value].Value, serializerState);
        snapshot.SetChild6RotationValue(ghostChild6RotationType[chunkDataLinkedEntityGroup[ent][7].Value].Value, serializerState);
        snapshot.SetChild6TranslationValue(ghostChild6TranslationType[chunkDataLinkedEntityGroup[ent][7].Value].Value, serializerState);
        snapshot.SetChild7RotationValue(ghostChild7RotationType[chunkDataLinkedEntityGroup[ent][8].Value].Value, serializerState);
        snapshot.SetChild7TranslationValue(ghostChild7TranslationType[chunkDataLinkedEntityGroup[ent][8].Value].Value, serializerState);
        snapshot.SetChild8RotationValue(ghostChild8RotationType[chunkDataLinkedEntityGroup[ent][9].Value].Value, serializerState);
        snapshot.SetChild8TranslationValue(ghostChild8TranslationType[chunkDataLinkedEntityGroup[ent][9].Value].Value, serializerState);
        snapshot.SetChild9RotationValue(ghostChild9RotationType[chunkDataLinkedEntityGroup[ent][10].Value].Value, serializerState);
        snapshot.SetChild9TranslationValue(ghostChild9TranslationType[chunkDataLinkedEntityGroup[ent][10].Value].Value, serializerState);
        snapshot.SetChild10RotationValue(ghostChild10RotationType[chunkDataLinkedEntityGroup[ent][11].Value].Value, serializerState);
        snapshot.SetChild10TranslationValue(ghostChild10TranslationType[chunkDataLinkedEntityGroup[ent][11].Value].Value, serializerState);
        snapshot.SetChild11RotationValue(ghostChild11RotationType[chunkDataLinkedEntityGroup[ent][12].Value].Value, serializerState);
        snapshot.SetChild11TranslationValue(ghostChild11TranslationType[chunkDataLinkedEntityGroup[ent][12].Value].Value, serializerState);
        snapshot.SetChild12RotationValue(ghostChild12RotationType[chunkDataLinkedEntityGroup[ent][13].Value].Value, serializerState);
        snapshot.SetChild12TranslationValue(ghostChild12TranslationType[chunkDataLinkedEntityGroup[ent][13].Value].Value, serializerState);
        snapshot.SetChild13RotationValue(ghostChild13RotationType[chunkDataLinkedEntityGroup[ent][14].Value].Value, serializerState);
        snapshot.SetChild13TranslationValue(ghostChild13TranslationType[chunkDataLinkedEntityGroup[ent][14].Value].Value, serializerState);
        snapshot.SetChild14RotationValue(ghostChild14RotationType[chunkDataLinkedEntityGroup[ent][15].Value].Value, serializerState);
        snapshot.SetChild14TranslationValue(ghostChild14TranslationType[chunkDataLinkedEntityGroup[ent][15].Value].Value, serializerState);
        snapshot.SetChild15RotationValue(ghostChild15RotationType[chunkDataLinkedEntityGroup[ent][16].Value].Value, serializerState);
        snapshot.SetChild15TranslationValue(ghostChild15TranslationType[chunkDataLinkedEntityGroup[ent][16].Value].Value, serializerState);
        snapshot.SetChild16RotationValue(ghostChild16RotationType[chunkDataLinkedEntityGroup[ent][17].Value].Value, serializerState);
        snapshot.SetChild16TranslationValue(ghostChild16TranslationType[chunkDataLinkedEntityGroup[ent][17].Value].Value, serializerState);
        snapshot.SetChild17RotationValue(ghostChild17RotationType[chunkDataLinkedEntityGroup[ent][18].Value].Value, serializerState);
        snapshot.SetChild17TranslationValue(ghostChild17TranslationType[chunkDataLinkedEntityGroup[ent][18].Value].Value, serializerState);
        snapshot.SetChild18RotationValue(ghostChild18RotationType[chunkDataLinkedEntityGroup[ent][19].Value].Value, serializerState);
        snapshot.SetChild18TranslationValue(ghostChild18TranslationType[chunkDataLinkedEntityGroup[ent][19].Value].Value, serializerState);
        snapshot.SetChild19RotationValue(ghostChild19RotationType[chunkDataLinkedEntityGroup[ent][20].Value].Value, serializerState);
        snapshot.SetChild19TranslationValue(ghostChild19TranslationType[chunkDataLinkedEntityGroup[ent][20].Value].Value, serializerState);
        snapshot.SetChild20RotationValue(ghostChild20RotationType[chunkDataLinkedEntityGroup[ent][21].Value].Value, serializerState);
        snapshot.SetChild20TranslationValue(ghostChild20TranslationType[chunkDataLinkedEntityGroup[ent][21].Value].Value, serializerState);
        snapshot.SetChild21RotationValue(ghostChild21RotationType[chunkDataLinkedEntityGroup[ent][22].Value].Value, serializerState);
        snapshot.SetChild21TranslationValue(ghostChild21TranslationType[chunkDataLinkedEntityGroup[ent][22].Value].Value, serializerState);
        snapshot.SetChild22RotationValue(ghostChild22RotationType[chunkDataLinkedEntityGroup[ent][23].Value].Value, serializerState);
        snapshot.SetChild22TranslationValue(ghostChild22TranslationType[chunkDataLinkedEntityGroup[ent][23].Value].Value, serializerState);
        snapshot.SetChild23RotationValue(ghostChild23RotationType[chunkDataLinkedEntityGroup[ent][24].Value].Value, serializerState);
        snapshot.SetChild23TranslationValue(ghostChild23TranslationType[chunkDataLinkedEntityGroup[ent][24].Value].Value, serializerState);
        snapshot.SetChild24RotationValue(ghostChild24RotationType[chunkDataLinkedEntityGroup[ent][25].Value].Value, serializerState);
        snapshot.SetChild24TranslationValue(ghostChild24TranslationType[chunkDataLinkedEntityGroup[ent][25].Value].Value, serializerState);
        snapshot.SetChild25RotationValue(ghostChild25RotationType[chunkDataLinkedEntityGroup[ent][26].Value].Value, serializerState);
        snapshot.SetChild25TranslationValue(ghostChild25TranslationType[chunkDataLinkedEntityGroup[ent][26].Value].Value, serializerState);
        snapshot.SetChild26RotationValue(ghostChild26RotationType[chunkDataLinkedEntityGroup[ent][27].Value].Value, serializerState);
        snapshot.SetChild26TranslationValue(ghostChild26TranslationType[chunkDataLinkedEntityGroup[ent][27].Value].Value, serializerState);
        snapshot.SetChild27RotationValue(ghostChild27RotationType[chunkDataLinkedEntityGroup[ent][28].Value].Value, serializerState);
        snapshot.SetChild27TranslationValue(ghostChild27TranslationType[chunkDataLinkedEntityGroup[ent][28].Value].Value, serializerState);
        snapshot.SetChild28RotationValue(ghostChild28RotationType[chunkDataLinkedEntityGroup[ent][29].Value].Value, serializerState);
        snapshot.SetChild28TranslationValue(ghostChild28TranslationType[chunkDataLinkedEntityGroup[ent][29].Value].Value, serializerState);
        snapshot.SetChild29RotationValue(ghostChild29RotationType[chunkDataLinkedEntityGroup[ent][30].Value].Value, serializerState);
        snapshot.SetChild29TranslationValue(ghostChild29TranslationType[chunkDataLinkedEntityGroup[ent][30].Value].Value, serializerState);
        snapshot.SetChild30RotationValue(ghostChild30RotationType[chunkDataLinkedEntityGroup[ent][31].Value].Value, serializerState);
        snapshot.SetChild30TranslationValue(ghostChild30TranslationType[chunkDataLinkedEntityGroup[ent][31].Value].Value, serializerState);
        snapshot.SetChild31RotationValue(ghostChild31RotationType[chunkDataLinkedEntityGroup[ent][32].Value].Value, serializerState);
        snapshot.SetChild31TranslationValue(ghostChild31TranslationType[chunkDataLinkedEntityGroup[ent][32].Value].Value, serializerState);
        snapshot.SetChild32RotationValue(ghostChild32RotationType[chunkDataLinkedEntityGroup[ent][33].Value].Value, serializerState);
        snapshot.SetChild32TranslationValue(ghostChild32TranslationType[chunkDataLinkedEntityGroup[ent][33].Value].Value, serializerState);
        snapshot.SetChild33RotationValue(ghostChild33RotationType[chunkDataLinkedEntityGroup[ent][34].Value].Value, serializerState);
        snapshot.SetChild33TranslationValue(ghostChild33TranslationType[chunkDataLinkedEntityGroup[ent][34].Value].Value, serializerState);
        snapshot.SetChild34RotationValue(ghostChild34RotationType[chunkDataLinkedEntityGroup[ent][35].Value].Value, serializerState);
        snapshot.SetChild34TranslationValue(ghostChild34TranslationType[chunkDataLinkedEntityGroup[ent][35].Value].Value, serializerState);
        snapshot.SetChild35RotationValue(ghostChild35RotationType[chunkDataLinkedEntityGroup[ent][36].Value].Value, serializerState);
        snapshot.SetChild35TranslationValue(ghostChild35TranslationType[chunkDataLinkedEntityGroup[ent][36].Value].Value, serializerState);
        snapshot.SetChild36RotationValue(ghostChild36RotationType[chunkDataLinkedEntityGroup[ent][37].Value].Value, serializerState);
        snapshot.SetChild36TranslationValue(ghostChild36TranslationType[chunkDataLinkedEntityGroup[ent][37].Value].Value, serializerState);
        snapshot.SetChild37RotationValue(ghostChild37RotationType[chunkDataLinkedEntityGroup[ent][38].Value].Value, serializerState);
        snapshot.SetChild37TranslationValue(ghostChild37TranslationType[chunkDataLinkedEntityGroup[ent][38].Value].Value, serializerState);
        snapshot.SetChild38RotationValue(ghostChild38RotationType[chunkDataLinkedEntityGroup[ent][39].Value].Value, serializerState);
        snapshot.SetChild38TranslationValue(ghostChild38TranslationType[chunkDataLinkedEntityGroup[ent][39].Value].Value, serializerState);
        snapshot.SetChild39RotationValue(ghostChild39RotationType[chunkDataLinkedEntityGroup[ent][40].Value].Value, serializerState);
        snapshot.SetChild39TranslationValue(ghostChild39TranslationType[chunkDataLinkedEntityGroup[ent][40].Value].Value, serializerState);
        snapshot.SetChild40RotationValue(ghostChild40RotationType[chunkDataLinkedEntityGroup[ent][41].Value].Value, serializerState);
        snapshot.SetChild40TranslationValue(ghostChild40TranslationType[chunkDataLinkedEntityGroup[ent][41].Value].Value, serializerState);
        snapshot.SetChild41RotationValue(ghostChild41RotationType[chunkDataLinkedEntityGroup[ent][42].Value].Value, serializerState);
        snapshot.SetChild41TranslationValue(ghostChild41TranslationType[chunkDataLinkedEntityGroup[ent][42].Value].Value, serializerState);
        snapshot.SetChild42RotationValue(ghostChild42RotationType[chunkDataLinkedEntityGroup[ent][43].Value].Value, serializerState);
        snapshot.SetChild42TranslationValue(ghostChild42TranslationType[chunkDataLinkedEntityGroup[ent][43].Value].Value, serializerState);
        snapshot.SetChild43RotationValue(ghostChild43RotationType[chunkDataLinkedEntityGroup[ent][44].Value].Value, serializerState);
        snapshot.SetChild43TranslationValue(ghostChild43TranslationType[chunkDataLinkedEntityGroup[ent][44].Value].Value, serializerState);
        snapshot.SetChild44RotationValue(ghostChild44RotationType[chunkDataLinkedEntityGroup[ent][45].Value].Value, serializerState);
        snapshot.SetChild44TranslationValue(ghostChild44TranslationType[chunkDataLinkedEntityGroup[ent][45].Value].Value, serializerState);
        snapshot.SetChild45RotationValue(ghostChild45RotationType[chunkDataLinkedEntityGroup[ent][46].Value].Value, serializerState);
        snapshot.SetChild45TranslationValue(ghostChild45TranslationType[chunkDataLinkedEntityGroup[ent][46].Value].Value, serializerState);
        snapshot.SetChild46RotationValue(ghostChild46RotationType[chunkDataLinkedEntityGroup[ent][47].Value].Value, serializerState);
        snapshot.SetChild46TranslationValue(ghostChild46TranslationType[chunkDataLinkedEntityGroup[ent][47].Value].Value, serializerState);
        snapshot.SetChild47RotationValue(ghostChild47RotationType[chunkDataLinkedEntityGroup[ent][48].Value].Value, serializerState);
        snapshot.SetChild47TranslationValue(ghostChild47TranslationType[chunkDataLinkedEntityGroup[ent][48].Value].Value, serializerState);
        snapshot.SetChild48RotationValue(ghostChild48RotationType[chunkDataLinkedEntityGroup[ent][49].Value].Value, serializerState);
        snapshot.SetChild48TranslationValue(ghostChild48TranslationType[chunkDataLinkedEntityGroup[ent][49].Value].Value, serializerState);
        snapshot.SetChild49RotationValue(ghostChild49RotationType[chunkDataLinkedEntityGroup[ent][50].Value].Value, serializerState);
        snapshot.SetChild49TranslationValue(ghostChild49TranslationType[chunkDataLinkedEntityGroup[ent][50].Value].Value, serializerState);
        snapshot.SetChild50RotationValue(ghostChild50RotationType[chunkDataLinkedEntityGroup[ent][51].Value].Value, serializerState);
        snapshot.SetChild50TranslationValue(ghostChild50TranslationType[chunkDataLinkedEntityGroup[ent][51].Value].Value, serializerState);
        snapshot.SetChild51RotationValue(ghostChild51RotationType[chunkDataLinkedEntityGroup[ent][52].Value].Value, serializerState);
        snapshot.SetChild51TranslationValue(ghostChild51TranslationType[chunkDataLinkedEntityGroup[ent][52].Value].Value, serializerState);
        snapshot.SetChild52RotationValue(ghostChild52RotationType[chunkDataLinkedEntityGroup[ent][53].Value].Value, serializerState);
        snapshot.SetChild52TranslationValue(ghostChild52TranslationType[chunkDataLinkedEntityGroup[ent][53].Value].Value, serializerState);
        snapshot.SetChild53RotationValue(ghostChild53RotationType[chunkDataLinkedEntityGroup[ent][54].Value].Value, serializerState);
        snapshot.SetChild53TranslationValue(ghostChild53TranslationType[chunkDataLinkedEntityGroup[ent][54].Value].Value, serializerState);
        snapshot.SetChild54RotationValue(ghostChild54RotationType[chunkDataLinkedEntityGroup[ent][55].Value].Value, serializerState);
        snapshot.SetChild54TranslationValue(ghostChild54TranslationType[chunkDataLinkedEntityGroup[ent][55].Value].Value, serializerState);
        snapshot.SetChild55RotationValue(ghostChild55RotationType[chunkDataLinkedEntityGroup[ent][56].Value].Value, serializerState);
        snapshot.SetChild55TranslationValue(ghostChild55TranslationType[chunkDataLinkedEntityGroup[ent][56].Value].Value, serializerState);
        snapshot.SetChild56RotationValue(ghostChild56RotationType[chunkDataLinkedEntityGroup[ent][57].Value].Value, serializerState);
        snapshot.SetChild56TranslationValue(ghostChild56TranslationType[chunkDataLinkedEntityGroup[ent][57].Value].Value, serializerState);
        snapshot.SetChild57RotationValue(ghostChild57RotationType[chunkDataLinkedEntityGroup[ent][58].Value].Value, serializerState);
        snapshot.SetChild57TranslationValue(ghostChild57TranslationType[chunkDataLinkedEntityGroup[ent][58].Value].Value, serializerState);
        snapshot.SetChild58RotationValue(ghostChild58RotationType[chunkDataLinkedEntityGroup[ent][59].Value].Value, serializerState);
        snapshot.SetChild58TranslationValue(ghostChild58TranslationType[chunkDataLinkedEntityGroup[ent][59].Value].Value, serializerState);
        snapshot.SetChild59RotationValue(ghostChild59RotationType[chunkDataLinkedEntityGroup[ent][60].Value].Value, serializerState);
        snapshot.SetChild59TranslationValue(ghostChild59TranslationType[chunkDataLinkedEntityGroup[ent][60].Value].Value, serializerState);
        snapshot.SetChild60RotationValue(ghostChild60RotationType[chunkDataLinkedEntityGroup[ent][61].Value].Value, serializerState);
        snapshot.SetChild60TranslationValue(ghostChild60TranslationType[chunkDataLinkedEntityGroup[ent][61].Value].Value, serializerState);
        snapshot.SetChild61RotationValue(ghostChild61RotationType[chunkDataLinkedEntityGroup[ent][62].Value].Value, serializerState);
        snapshot.SetChild61TranslationValue(ghostChild61TranslationType[chunkDataLinkedEntityGroup[ent][62].Value].Value, serializerState);
        snapshot.SetChild62RotationValue(ghostChild62RotationType[chunkDataLinkedEntityGroup[ent][63].Value].Value, serializerState);
        snapshot.SetChild62TranslationValue(ghostChild62TranslationType[chunkDataLinkedEntityGroup[ent][63].Value].Value, serializerState);
        snapshot.SetChild63RotationValue(ghostChild63RotationType[chunkDataLinkedEntityGroup[ent][64].Value].Value, serializerState);
        snapshot.SetChild63TranslationValue(ghostChild63TranslationType[chunkDataLinkedEntityGroup[ent][64].Value].Value, serializerState);
        snapshot.SetChild64RotationValue(ghostChild64RotationType[chunkDataLinkedEntityGroup[ent][65].Value].Value, serializerState);
        snapshot.SetChild64TranslationValue(ghostChild64TranslationType[chunkDataLinkedEntityGroup[ent][65].Value].Value, serializerState);
        snapshot.SetChild65RotationValue(ghostChild65RotationType[chunkDataLinkedEntityGroup[ent][66].Value].Value, serializerState);
        snapshot.SetChild65TranslationValue(ghostChild65TranslationType[chunkDataLinkedEntityGroup[ent][66].Value].Value, serializerState);
        snapshot.SetChild66RotationValue(ghostChild66RotationType[chunkDataLinkedEntityGroup[ent][67].Value].Value, serializerState);
        snapshot.SetChild66TranslationValue(ghostChild66TranslationType[chunkDataLinkedEntityGroup[ent][67].Value].Value, serializerState);
        snapshot.SetChild67RotationValue(ghostChild67RotationType[chunkDataLinkedEntityGroup[ent][68].Value].Value, serializerState);
        snapshot.SetChild67TranslationValue(ghostChild67TranslationType[chunkDataLinkedEntityGroup[ent][68].Value].Value, serializerState);
        snapshot.SetChild68RotationValue(ghostChild68RotationType[chunkDataLinkedEntityGroup[ent][69].Value].Value, serializerState);
        snapshot.SetChild68TranslationValue(ghostChild68TranslationType[chunkDataLinkedEntityGroup[ent][69].Value].Value, serializerState);
        snapshot.SetChild69RotationValue(ghostChild69RotationType[chunkDataLinkedEntityGroup[ent][70].Value].Value, serializerState);
        snapshot.SetChild69TranslationValue(ghostChild69TranslationType[chunkDataLinkedEntityGroup[ent][70].Value].Value, serializerState);
        snapshot.SetChild70RotationValue(ghostChild70RotationType[chunkDataLinkedEntityGroup[ent][71].Value].Value, serializerState);
        snapshot.SetChild70TranslationValue(ghostChild70TranslationType[chunkDataLinkedEntityGroup[ent][71].Value].Value, serializerState);
        snapshot.SetChild71RotationValue(ghostChild71RotationType[chunkDataLinkedEntityGroup[ent][72].Value].Value, serializerState);
        snapshot.SetChild71TranslationValue(ghostChild71TranslationType[chunkDataLinkedEntityGroup[ent][72].Value].Value, serializerState);
        snapshot.SetChild72RotationValue(ghostChild72RotationType[chunkDataLinkedEntityGroup[ent][73].Value].Value, serializerState);
        snapshot.SetChild72TranslationValue(ghostChild72TranslationType[chunkDataLinkedEntityGroup[ent][73].Value].Value, serializerState);
        snapshot.SetChild73RotationValue(ghostChild73RotationType[chunkDataLinkedEntityGroup[ent][74].Value].Value, serializerState);
        snapshot.SetChild73TranslationValue(ghostChild73TranslationType[chunkDataLinkedEntityGroup[ent][74].Value].Value, serializerState);
        snapshot.SetChild74RotationValue(ghostChild74RotationType[chunkDataLinkedEntityGroup[ent][75].Value].Value, serializerState);
        snapshot.SetChild74TranslationValue(ghostChild74TranslationType[chunkDataLinkedEntityGroup[ent][75].Value].Value, serializerState);
        snapshot.SetChild75RotationValue(ghostChild75RotationType[chunkDataLinkedEntityGroup[ent][76].Value].Value, serializerState);
        snapshot.SetChild75TranslationValue(ghostChild75TranslationType[chunkDataLinkedEntityGroup[ent][76].Value].Value, serializerState);
        snapshot.SetChild76RotationValue(ghostChild76RotationType[chunkDataLinkedEntityGroup[ent][77].Value].Value, serializerState);
        snapshot.SetChild76TranslationValue(ghostChild76TranslationType[chunkDataLinkedEntityGroup[ent][77].Value].Value, serializerState);
        snapshot.SetChild77RotationValue(ghostChild77RotationType[chunkDataLinkedEntityGroup[ent][78].Value].Value, serializerState);
        snapshot.SetChild77TranslationValue(ghostChild77TranslationType[chunkDataLinkedEntityGroup[ent][78].Value].Value, serializerState);
        snapshot.SetChild78RotationValue(ghostChild78RotationType[chunkDataLinkedEntityGroup[ent][79].Value].Value, serializerState);
        snapshot.SetChild78TranslationValue(ghostChild78TranslationType[chunkDataLinkedEntityGroup[ent][79].Value].Value, serializerState);
        snapshot.SetChild79RotationValue(ghostChild79RotationType[chunkDataLinkedEntityGroup[ent][80].Value].Value, serializerState);
        snapshot.SetChild79TranslationValue(ghostChild79TranslationType[chunkDataLinkedEntityGroup[ent][80].Value].Value, serializerState);
        snapshot.SetChild80RotationValue(ghostChild80RotationType[chunkDataLinkedEntityGroup[ent][81].Value].Value, serializerState);
        snapshot.SetChild80TranslationValue(ghostChild80TranslationType[chunkDataLinkedEntityGroup[ent][81].Value].Value, serializerState);
        snapshot.SetChild81RotationValue(ghostChild81RotationType[chunkDataLinkedEntityGroup[ent][82].Value].Value, serializerState);
        snapshot.SetChild81TranslationValue(ghostChild81TranslationType[chunkDataLinkedEntityGroup[ent][82].Value].Value, serializerState);
        snapshot.SetChild82RotationValue(ghostChild82RotationType[chunkDataLinkedEntityGroup[ent][83].Value].Value, serializerState);
        snapshot.SetChild82TranslationValue(ghostChild82TranslationType[chunkDataLinkedEntityGroup[ent][83].Value].Value, serializerState);
        snapshot.SetChild83RotationValue(ghostChild83RotationType[chunkDataLinkedEntityGroup[ent][84].Value].Value, serializerState);
        snapshot.SetChild83TranslationValue(ghostChild83TranslationType[chunkDataLinkedEntityGroup[ent][84].Value].Value, serializerState);
        snapshot.SetChild84RotationValue(ghostChild84RotationType[chunkDataLinkedEntityGroup[ent][85].Value].Value, serializerState);
        snapshot.SetChild84TranslationValue(ghostChild84TranslationType[chunkDataLinkedEntityGroup[ent][85].Value].Value, serializerState);
        snapshot.SetChild85RotationValue(ghostChild85RotationType[chunkDataLinkedEntityGroup[ent][86].Value].Value, serializerState);
        snapshot.SetChild85TranslationValue(ghostChild85TranslationType[chunkDataLinkedEntityGroup[ent][86].Value].Value, serializerState);
        snapshot.SetChild86RotationValue(ghostChild86RotationType[chunkDataLinkedEntityGroup[ent][87].Value].Value, serializerState);
        snapshot.SetChild86TranslationValue(ghostChild86TranslationType[chunkDataLinkedEntityGroup[ent][87].Value].Value, serializerState);
    }
}
